env:
  global:
    - CC_TEST_REPORTER_ID=52f220bfb08723b95888e5c97dbfc3cafd3bcdfe3300d972235a3a4a55ba824d

sudo: false

language: php

php:
  - 7.1
  - 7.2

before_install:
  - composer self-update

install:
  - travis_retry composer update

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - echo 'date.timezone = "Europe/London"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - vendor/bin/phpcs --standard=PSR2 --warning-severity=0 src
  - vendor/bin/phpstan analyse -l 7 src
  - vendor/bin/phpunit --coverage-clover clover.xml

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
